#! /bin/sh

# Fix cursor
xsetroot -cursor_name catppuccin lavender &

# Keybinds 
pgrep -x sxhkd > /dev/null || sxhkd &

# polkit
# lxsession &

# status bar
$HOME/.config/polybar/launch.sh &

# compositor
picom -fb --experimental-backends --backend glx &

# wallpaper
feh --bg-scale ~/.config/bspwm/wallpaper.png &

# monitor Rules
bspc monitor HDMI-0 -d I II III IV V 				# Workspaces for external monitor
bspc monitor eDP-1-1 -d VI VII VIII IX X			# Workspaces for internal monitor

#
# GAPS
#

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#
# Colors
#

bspc config normal_border_color 		"#575268"
bspc config focused_border_color		"#C9CBFF"

#
# Application Rules
#

bspc rule -a Pcmanfm state=floating
bspc rule -a Zathura state=tiled

# Launch apps on specific workspaces
bspc rule -a Spotify desktop=^5 state=tiled

